av_pilot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('collection.urls')),
    path('filter', include('filter.urls')),
    path('admin/', admin.site.urls),
]

collection/urls.py
from collection.views import MovieList, MovieDetail
from django.urls import path

app_name = 'collection'
urlpatterns = [
    path('movies', MovieList.as_view(), name='movie-list'),
    path('movies/<int:pk>', MovieDetail.as_view(), name='movie-detail'),
]

filter/urls.py
from filter.views import FilterList
from django.urls import path

app_name = 'filter'
urlpatterns = [
    path('', FilterList.as_view(), name='filter-list'),
]

collection/models.py
from django.db import models


class Movie(models.Model):
    dvd_id = models.CharField(max_length=200)
    title = models.CharField(max_length=200, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)


class Category(models.Model):
    title = models.CharField(max_length=200)
    movies = models.ManyToManyField(Movie)

filter/models.py
from django.db import models

# Create your models here.

collection/views.py
from django.views import generic

from collection.models import Movie, Category


class MovieList(generic.ListView):
    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class MovieDetail(generic.DetailView):
    model = Movie

filter/views.py
from copy import deepcopy

from django.core.handlers.wsgi import WSGIRequest
from django.db.models import QuerySet
from django.views import generic

from collection.models import Movie, Category


class FilterList(generic.ListView):
    model = Movie

    def __init__(self, **kwargs):
        self.category_ids = set()
        super().__init__(**kwargs)

    def get(self, request: WSGIRequest, *args, **kwargs):
        self.set_category_ids(request)
        self.set_queryset()
        return super().get(request, *args, **kwargs)

    def set_category_ids(self, request: WSGIRequest):
        category_ids: list = request.GET.getlist('category')
        self.category_ids = set(category_ids)

    def set_queryset(self):
        movies = Movie.objects.all()
        for a_category in self.category_ids:
            movies = movies.filter(category=a_category)
        self.queryset = movies

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = self.get_movies_categories()
        return context

    def get_movies_categories(self):
        movie_ids = self.queryset.values_list('id', flat=True)
        categories = Category.objects.filter(movies__in=movie_ids)
        categories = queryset_to_dict(categories)
        return self.clean_categories(categories)

    @staticmethod
    def clean_categories(categories) -> dict:
        result = dict()
        for a_categories in categories:
            detail = result.setdefault(a_categories, {})
            detail["count"] = detail.setdefault("count", 0) + 1
        return result

    @staticmethod
    def add_url(categories: dict, querystring_category: list):
        # TODO: using this method in somewhere
        k: Category
        v: dict
        for k, v in categories.items():
            c_id = k.id
            link_ids = deepcopy(querystring_category)
            if c_id in link_ids:
                link_ids.remove(c_id)
            else:
                link_ids.append(c_id)
            v["querystring"] = "?categorys=" + "&categorys=".join(link_ids)


def add_or_remove(ids: set, check_id: str) -> set:
    result = deepcopy(ids)
    if check_id in ids:
        result.remove(check_id)
    else:
        result.add(check_id)
    return result


def queryset_to_dict(queryset: QuerySet) -> dict:
    result = dict()
    for a_query in queryset:
        result[a_query] = dict()
    return result


class Categories:
    def __init__(self, categories: QuerySet):
        self.origin = categories
        self.value = dict()

    def set_value(self):
        self.value = queryset_to_dict(self.origin)

    def set_count(self):
        for a_categories in self.origin:
            detail = self.value[a_categories]
            detail["count"] = detail.get("count", 0) + 1

collection/templates/collection/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

collection/templates/collection/movie_detail.html
{% extends "collection/base.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <p>DVD ID: {{ object.dvd_id }}</p>
    <p>Release Date: {{ object.release_date }}</p>
    {% for category in object.category_set.all %}
        <p>Category Set: {{ category.name }}</p>
    {% endfor %}
{% endblock %}

collection/templates/collection/movie_list.html
{% extends "collection/base.html" %}

{% block content %}
    <h2>Movies</h2>
    <dl>
        {% for movie in object_list %}
            <dt>
                <a href="{% url 'collection:movie-detail' movie.id %}">
                    {{ movie.id }}
                </a>
            </dt>
            <dd>{{ movie.dvd_id }}</dd>
            <dd>{{ movie.title }}</dd>
            <dd>{{ movie.release_date }}</dd>
        {% endfor %}
    </dl>
    <h2>Categories</h2>
    <dl>
        {% for a_category, detail in category_list.items %}
            <dt>
{#                <a href="{% url 'collection:movie-detail' movie.id %}">#}
{#                    {{ movie.id }}#}
{#                </a>#}
                {{ a_category.id }}
            </dt>
            <dd>{{ a_category.title }}</dd>
            <dd>{{ detail.count }}</dd>
            <dd>{{ detail.querystring }}</dd>
        {% endfor %}
    </dl>
{% endblock %}

templates/movie_formset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
{#    {{ formset }}#}
    {% for form in formset.forms %}
        <div>{{ form.as_ul }}</div>
    {% endfor %}
    <input type="submit" value="Submit"/>
</form>
</body>
</html>